GET http://127.0.0.1:5000/users 

###

GET http://127.0.0.1:5000/users/3

###
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
    "firstName": "Test4",
    "lastName": "Userovich4",
    "email": "test3@gmail.com"
}